language: d
d:
  - dmd-2.090.0
  - dmd-2.085.0
  - dmd-2.080.0
  - dmd-2.075.0
  - dmd-2.070.0
  - dmd-2.069.0
  - dmd-2.068.2
  - dmd-2.068.1
  - ldc-1.20.0-beta1
  - ldc-1.19.0
  - ldc-1.16.0
  - gdc-2.081

matrix:

sudo: false
